import { useState } from 'react'
import { Folder, ClipboardCheck, Users, Wallet, BarChart2, TrendingUp, Download, RotateCcw } from 'lucide-react'

export default function ReportsPage() {
  const [reportType, setReportType] = useState('')
  const [project, setProject] = useState('')
  const [dateFrom, setDateFrom] = useState('')
  const [dateTo, setDateTo] = useState('')

  const resetFilters = () => {
    setReportType(''); setProject(''); setDateFrom(''); setDateTo('')
  }

  const handleDownload = (name, format = null) => {
    let ext = format;
    if (!ext) {
      const lower = name.toLowerCase();
      if (lower.includes('status') || lower.includes('budget') || lower.includes('utilization')) ext = 'csv';
      else if (lower.includes('workload')) ext = 'docx';
      else ext = 'pdf';
    } else {
      ext = ext.toLowerCase();
      if (ext === 'excel') ext = 'csv';
      if (ext === 'word') ext = 'docx';
    }

    let type = 'text/plain';
    if (ext === 'pdf') type = 'application/pdf';
    else if (ext === 'xlsx') type = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    else if (ext === 'docx') type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    else if (ext === 'csv') type = 'text/csv';

    const text = `Report: ${name}\nGenerated by Planora.`
    const blob = new Blob([text], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${name.replace(/\s+/g, '_')}.${ext}`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const reports = [
    { title: 'Project Summary Report', desc: 'Overview of all projects, status, progress and key milestones.', icon: Folder },
    { title: 'Task Status Report', desc: 'Summary of tasks by status, priority and completion.', icon: ClipboardCheck },
    { title: 'Team Workload Report', desc: 'Workload distribution and performance of team members.', icon: Users },
    { title: 'Budget Report', desc: 'Budget overview, allocation vs utilization and balance.', icon: Wallet },
    { title: 'Resource Utilization Report', desc: 'Resource allocation and utilization across projects.', icon: BarChart2 },
    { title: 'Project Progress Report', desc: 'Overall progress of projects with key milestones and deadlines.', icon: TrendingUp },
  ]

  const generatedReports = [
    { id: 1, name: 'Project Summary - May 2024', type: 'Project Summary', project: 'Website Redesign', date: '10 May 2024, 10:30 AM', by: 'Rahul Mehta', format: 'pdf' },
    { id: 2, name: 'Task Status - May 2024', type: 'Task Status', project: 'Mobile App Development', date: '09 May 2024, 04:15 PM', by: 'Rahul Mehta', format: 'csv' },
    { id: 3, name: 'Budget Report - Q2 2024', type: 'Budget', project: 'All Projects', date: '08 May 2024, 11:20 AM', by: 'Rahul Mehta', format: 'pdf' },
  ]

  return (
    <div>
      <div className="page-header" style={{ marginBottom: 20 }}>
        <div>
          <h1 className="page-heading">Reports</h1>

        </div>
      </div>

      <div className="card" style={{ marginBottom: 24, padding: 20 }}>
        <div style={{ display: 'flex', gap: 16, alignItems: 'flex-end', flexWrap: 'wrap' }}>
          <div style={{ flex: 1, minWidth: 200 }}>
            <div style={{ fontSize: '0.75rem', fontWeight: 600, marginBottom: 6 }}>Report Type</div>
            <select className="form-select" value={reportType} onChange={e => setReportType(e.target.value)}>
              <option value="">Select Report Type</option>
              <option value="SUMMARY">Project Summary</option>
              <option value="TASK">Task Status</option>
              <option value="BUDGET">Budget Report</option>
            </select>
          </div>
          <div style={{ flex: 1, minWidth: 200 }}>
            <div style={{ fontSize: '0.75rem', fontWeight: 600, marginBottom: 6 }}>Project</div>
            <select className="form-select" value={project} onChange={e => setProject(e.target.value)}>
              <option value="">All Projects</option>
              <option value="P1">Website Redesign</option>
              <option value="P2">Mobile App Development</option>
            </select>
          </div>
          <div style={{ flex: 1, minWidth: 150 }}>
            <div style={{ fontSize: '0.75rem', fontWeight: 600, marginBottom: 6 }}>Date From</div>
            <input type="date" className="form-input" value={dateFrom} onChange={e => setDateFrom(e.target.value)} />
          </div>
          <div style={{ flex: 1, minWidth: 150 }}>
            <div style={{ fontSize: '0.75rem', fontWeight: 600, marginBottom: 6 }}>Date To</div>
            <input type="date" className="form-input" value={dateTo} onChange={e => setDateTo(e.target.value)} />
          </div>
          <button className="btn btn-outline" style={{ height: 38, whiteSpace: 'nowrap', color: '#7c3aed', borderColor: '#7c3aed' }} onClick={resetFilters}>
            <RotateCcw size={13} style={{ marginRight: 6 }} /> Clear Filters
          </button>
        </div>
      </div>

      <h3 style={{ fontSize: '1.05rem', fontWeight: 600, marginBottom: 16 }}>Available Reports</h3>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, marginBottom: 32 }}>
        {reports.map((r, i) => (
          <div key={i} className="card" style={{ padding: 24, display: 'flex', gap: 16, alignItems: 'flex-start' }}>
            <div style={{ width: 48, height: 48, borderRadius: '12px', background: '#f5f3ff', color: '#7c3aed', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
              <r.icon size={24} strokeWidth={1.5} />
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
              <div style={{ fontWeight: 600, fontSize: '0.9rem', marginBottom: 6 }}>{r.title}</div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: 16, lineHeight: 1.5, flex: 1 }}>{r.desc}</div>
              <button className="btn btn-outline btn-sm" onClick={() => handleDownload(r.title)} style={{ alignSelf: 'flex-start', color: '#7c3aed', borderColor: '#e9d5ff', padding: '6px 14px', background: 'transparent' }}>
                <Download size={14} style={{ marginRight: 6 }} /> Download
              </button>
            </div>
          </div>
        ))}
      </div>

      <h3 style={{ fontSize: '1.05rem', fontWeight: 600, marginBottom: 16 }}>Generated Reports</h3>
      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        <div className="table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>Report Name</th>
                <th>Type</th>
                <th>Project</th>
                <th>Generated On</th>
                <th>Generated By</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {generatedReports.map(g => (
                <tr key={g.id}>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                      <div style={{ width: 28, height: 28, borderRadius: 6, background: g.format === 'pdf' ? '#fee2e2' : '#dcfce7', color: g.format === 'pdf' ? '#ef4444' : '#10b981', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '0.6rem', fontWeight: 700 }}>
                        {g.format.toUpperCase()}
                      </div>
                      <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{g.name}</div>
                    </div>
                  </td>
                  <td style={{ fontSize: '0.85rem' }}>{g.type}</td>
                  <td style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>{g.project}</td>
                  <td style={{ fontSize: '0.85rem' }}>{g.date}</td>
                  <td style={{ fontSize: '0.85rem' }}>{g.by}</td>
                  <td>
                    <div style={{ display: 'flex', gap: 12, alignItems: 'center', justifyContent: 'center' }}>
                      <button onClick={() => handleDownload(g.name, g.format)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#7c3aed', display: 'flex' }} title="Download Report">
                        <Download size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="pagination">
          <span>Showing 1 to 3 of 3 reports</span>
          <div className="pag-controls">
            <button className="pag-btn" disabled>‹</button>
            <button className="pag-btn active">1</button>
            <button className="pag-btn" disabled>›</button>
          </div>
        </div>
      </div>
    </div>
  )
}
